### ISSUE TITLE
Run custom script using appservice-build

### ISSUE THREAD

**Issue by erfannariman** [Azure/appservice-build#34]
I would like to install a private repository when building a webapp. Right now we use a GITHUB ACCES TOKEN when deploying to a standard ubuntu server as following:

```yaml
name: My App
on:
  push:
    branches:
      - main
env:
  AZURE_WEBAPP_NAME: my-app
  AZURE_WEBAPP_PACKAGE_PATH: '.'
  PYTHON_VERSION: '3.8' # supports 3.6, 3.7, 3.8)
jobs:
  build-and-deploy-to-Azure:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@master
    - name: Setup Python ${{ env.PYTHON_VERSION }} Environment
      uses: actions/setup-python@v2
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    - name: 'Install dependencies'
      run: |
        python -m pip install --upgrade pip
        git config --global url."https://${{ secrets.ACCESS_TOKEN }}@github".insteadOf https://github
        pip install -r requirements.txt
    - name: 'Deploy to Azure WebApp'
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
```

Notice the
```commandline 
git config --global url."https://${{ secrets.ACCESS_TOKEN }}@github".insteadOf https://github
```
And in our `requirements.txt` we have:
```
git+https://github.com/orgname/reponame.git#egg=reponame
```

---

But obviously this will fail with `appservice-build` because it has no access to our `secrets.ACCESS_TOKEN` during runtime. Is there any way to get this working while deploying to Azure Web Apps through GH Actions?
