### ISSUE TITLE
No ARM control over build properties

### ISSUE THREAD

**Issue by brentarias** [Azure/appservice-build#41]
There is a critical github workflow initialization capability which exists for Azure static websites, that apparently does not exist for Azure App Services.  According to the [static website ARM grammar](https://learn.microsoft.com/en-us/azure/templates/microsoft.web/staticsites?pivots=deployment-language-arm-template), the following path properties can be specified in the static website ARM template: 

```JSON
    "repositoryToken": "string",
    "repositoryUrl": "string",
    "buildProperties": {
      "appLocation": "string",  //path within the repo, to the app that must be built.
      "apiLocation": "string",   //path to API code, if applicable.
      "outputLocation": "string" //path to the bits, after build completes.
    }
```
When a static website ARM template is deployed, a github workflow action file is automatically created and checked into the repo.  That workflow action file is populated with the `buildProperties` supplied above, as shown below:

```yaml
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_YELLOW_DESERT_083CEBA0F }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "/aliriam-rfp-poc" # App source code path
          api_location: "" # Api source code path - optional
          output_location: "dist/aliriam-rfp-poc" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######
```
In contrast, the Azure App Service ARM grammar does not have the ability to specify these build-related paths.  Thus the github workflow file that is generated - does not have the correct app path(s).  It is automatically a failed deployment. To be clear, unlike the static website ARM grammar, the App Service ARM grammar does not directly describe any repo properties.  Instead it depends on a `Microsoft.Web/sites/sourcecontrols` [sub-grammar](https://learn.microsoft.com/en-us/azure/templates/microsoft.web/2022-03-01/sites/sourcecontrols?pivots=deployment-language-arm-template), which unfortunately also does not have build-path properties.

Furthermore, the Azure portal App Service "create resource" blade also does not seem to support such build properties.  Apparently the only way I can set these build-path properties, is by hand-editing the github workflow file after my Azure App Service resource has already been deployed.  This is very awkward, and largely undermines the point of having ARM templates.

Indeed, the "awkward" goes a step further because the auto-generated github workflow file contains default references to "myapp", which has no relationship to what my app is called, or the folders used by my app.  Notice:

```yaml
      - name: dotnet publish
        run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp
```
Even if there was a way to compensate by embedding the proper build path into to the `DOTNET_ROOT` variable, the appended `myapp` will still be wrong.

So again, it looks like I'm stuck doing post-deployment manual fixes to the auto-generated github workflow file.  Is there some trick I am overlooking?  Right now this looks like a critical missing capability for ARM deployments.
